language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm test
deploy:
  provider: heroku
  api_key: $herokuKey
  app:
    master: blooming-atoll-68899
    production: blooming-atoll-68899